{{- if .Values.initialUser.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "trifle.fullname" . }}-init-user
  labels:
    {{- include "trifle.labels" . | nindent 4 }}
    app.kubernetes.io/component: init-user
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "trifle.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: init-user
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: init-user
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            - "./bin/trifle"
            - "eval"
            - "Trifle.Release.create_initial_user()"
          env:
            {{- range $key, $value := .Values.app.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" . }}-secret
                  key: database-url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" . }}-secret
                  key: secret-key-base
            {{- if .Values.app.dbEncryptionKey }}
            - name: TRIFLE_DB_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" . }}-secret
                  key: db-encryption-key
            {{- end }}
            - name: INITIAL_USER_EMAIL
              value: {{ .Values.initialUser.email | quote }}
            - name: INITIAL_USER_PASSWORD
              value: {{ .Values.initialUser.password | quote }}
            - name: INITIAL_USER_ADMIN
              value: {{ .Values.initialUser.admin | quote }}
            - name: TRIFLE_DEPLOYMENT_MODE
              value: {{ .Values.app.deploymentMode | quote }}
            {{- with .Values.app.logLevel }}
            - name: LOGGER_LEVEL
              value: {{ . | quote }}
            {{- end }}
            - name: MAILER_ADAPTER
              value: {{ .Values.app.mailer.adapter | quote }}
            - name: MAILER_FROM_NAME
              value: {{ .Values.app.mailer.from.name | quote }}
            - name: MAILER_FROM_EMAIL
              value: {{ .Values.app.mailer.from.email | quote }}
            {{- with .Values.app.mailer.smtp.relay }}
            - name: SMTP_RELAY
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.app.mailer.smtp.port }}
            - name: SMTP_PORT
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.app.mailer.smtp.auth }}
            - name: SMTP_AUTH
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.app.mailer.smtp.tls }}
            - name: SMTP_TLS
              value: {{ . | quote }}
            {{- end }}
            {{- if hasKey .Values.app.mailer.smtp "ssl" }}
            - name: SMTP_SSL
              value: {{ .Values.app.mailer.smtp.ssl | quote }}
            {{- end }}
            {{- with .Values.app.mailer.smtp.retries }}
            - name: SMTP_RETRIES
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.app.mailer.smtp.username }}
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" $ }}-secret
                  key: smtp-username
            {{- end }}
            {{- with .Values.app.mailer.smtp.password }}
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" $ }}-secret
                  key: smtp-password
            {{- end }}
            {{- with .Values.app.mailer.postmark.apiKey }}
            - name: POSTMARK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" $ }}-secret
                  key: postmark-api-key
            {{- end }}
            {{- with .Values.app.mailer.sendgrid.apiKey }}
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" $ }}-secret
                  key: sendgrid-api-key
            {{- end }}
            {{- with .Values.app.mailer.mailgun.domain }}
            - name: MAILGUN_DOMAIN
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.app.mailer.mailgun.baseUrl }}
            - name: MAILGUN_BASE_URL
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.app.mailer.mailgun.apiKey }}
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" $ }}-secret
                  key: mailgun-api-key
            {{- end }}
            {{- with .Values.app.mailer.sendinblue.apiKey }}
            - name: SENDINBLUE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" $ }}-secret
                  key: sendinblue-api-key
            {{- end }}
            {{- with .Values.app.stripe.secretKey }}
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" $ }}-secret
                  key: stripe-secret-key
            {{- end }}
            {{- with .Values.app.stripe.webhookSigningSecret }}
            - name: STRIPE_WEBHOOK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" $ }}-secret
                  key: stripe-webhook-signing-secret
            {{- end }}
            {{- with .Values.app.stripe.portalConfigurationId }}
            - name: STRIPE_PORTAL_CONFIGURATION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" $ }}-secret
                  key: stripe-portal-configuration-id
            {{- end }}
            {{- with .Values.app.slack.clientId }}
            - name: SLACK_CLIENT_ID
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.app.slack.clientSecret }}
            - name: SLACK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" $ }}-secret
                  key: slack-client-secret
            {{- end }}
            {{- with .Values.app.slack.signingSecret }}
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" $ }}-secret
                  key: slack-signing-secret
            {{- end }}
            {{- with .Values.app.slack.redirectUri }}
            - name: SLACK_REDIRECT_URI
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.app.slack.scopes }}
            - name: SLACK_SCOPES
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.app.googleOAuth.clientId }}
            - name: GOOGLE_OAUTH_CLIENT_ID
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.app.googleOAuth.clientSecret }}
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "trifle.fullname" $ }}-secret
                  key: google-oauth-client-secret
            {{- end }}
            {{- with .Values.app.googleOAuth.redirectUri }}
            - name: GOOGLE_OAUTH_REDIRECT_URI
              value: {{ . | quote }}
            {{- end }}
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
{{- end }}
