apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trifle.fullname" . }}-secret
  labels:
    {{- include "trifle.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key-base: {{ .Values.app.secretKeyBase | b64enc }}
  database-url: {{ include "trifle.databaseUrl" . | trim | b64enc }}
  {{- if .Values.app.honeybadger.apiKey }}
  honeybadger-api-key: {{ .Values.app.honeybadger.apiKey | b64enc }}
  {{- end }}