apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trifle.fullname" . }}-secret
  labels:
    {{- include "trifle.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key-base: {{ .Values.app.secretKeyBase | b64enc }}
  {{- if .Values.app.dbEncryptionKey }}
  db-encryption-key: {{ .Values.app.dbEncryptionKey | b64enc }}
  {{- end }}
  database-url: {{ include "trifle.databaseUrl" . | trim | b64enc }}
  {{- if .Values.app.honeybadger.apiKey }}
  honeybadger-api-key: {{ .Values.app.honeybadger.apiKey | b64enc }}
  {{- end }}
  {{- if and .Values.app.appsignal.enabled .Values.app.appsignal.pushApiKey }}
  appsignal-push-api-key: {{ .Values.app.appsignal.pushApiKey | b64enc }}
  {{- end }}
  {{- if and .Values.app.newrelic.enabled .Values.app.newrelic.licenseKey }}
  newrelic-license-key: {{ .Values.app.newrelic.licenseKey | b64enc }}
  {{- end }}
  {{- with .Values.app.mailer.smtp.username }}
  smtp-username: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.mailer.smtp.password }}
  smtp-password: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.mailer.postmark.apiKey }}
  postmark-api-key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.mailer.sendgrid.apiKey }}
  sendgrid-api-key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.mailer.mailgun.apiKey }}
  mailgun-api-key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.mailer.sendinblue.apiKey }}
  sendinblue-api-key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.slack.clientSecret }}
  slack-client-secret: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.slack.signingSecret }}
  slack-signing-secret: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.googleOAuth.clientSecret }}
  google-oauth-client-secret: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.stripe.secretKey }}
  stripe-secret-key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.stripe.webhookSigningSecret }}
  stripe-webhook-signing-secret: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.stripe.portalConfigurationId }}
  stripe-portal-configuration-id: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.openai.apiKey }}
  openai-api-key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.mongodbUrl }}
  mongodb-url: {{ . | b64enc }}
  {{- end }}
