apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trifle.fullname" . }}-secret
  labels:
    {{- include "trifle.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key-base: {{ .Values.app.secretKeyBase | b64enc }}
  database-url: {{ include "trifle.databaseUrl" . | trim | b64enc }}
  {{- if .Values.app.honeybadger.apiKey }}
  honeybadger-api-key: {{ .Values.app.honeybadger.apiKey | b64enc }}
  {{- end }}
  {{- if and .Values.app.appsignal.enabled .Values.app.appsignal.pushApiKey }}
  appsignal-push-api-key: {{ .Values.app.appsignal.pushApiKey | b64enc }}
  {{- end }}
  {{- with .Values.app.mailer.smtp.username }}
  smtp-username: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.mailer.smtp.password }}
  smtp-password: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.mailer.postmark.apiKey }}
  postmark-api-key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.mailer.sendgrid.apiKey }}
  sendgrid-api-key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.mailer.mailgun.apiKey }}
  mailgun-api-key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.mailer.sendinblue.apiKey }}
  sendinblue-api-key: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.app.openai.apiKey }}
  openai-api-key: {{ . | b64enc }}
  {{- end }}
