version: "3.7"
name: "trifle"
services:
  redis:
    image: redis:latest
    restart: unless-stopped
  mongo:
    image: mongo:latest
    restart: unless-stopped
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: trifle_dev
    restart: unless-stopped
  app:
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - .env
    build:
      context: .
      dockerfile: .devops/docker/local/Dockerfile
    depends_on:
      - redis
      - mongo
      - postgres
    environment:
      PGHOST: postgres
      PGUSER: postgres
      REDIS_HOST: redis
      REDIS_URL: redis://redis:6379
    ports:
      - 4000:4000
    volumes:
      - .:/workspaces/trifle:cached
      - trifle_deps:/workspaces/trifle/deps
      - trifle_build:/workspaces/trifle/_build
      - ../trifle_stats:/workspaces/trifle_stats
    working_dir: /workspaces/trifle
volumes:
  trifle_deps:
  trifle_build:
